#! /bin/bash

# Copyright 2024 Denis Salem
#
# This file is part of uWifi.
#
# uWifi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# uWifi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with uWifi. If not, see <http://www.gnu.org/licenses/>.

uWifiVersion="1.0.0"

function abort {
  echo "uWifi: $1"
  exit $2
}

wpa_supplicant -v >/dev/null 2>&1 || abort "wpa_supplicant isn't installed" 255
dhcpcd --version >/dev/null 2>&1 || abort "dhcpcd isn't installed" 255
iw --version >/dev/null 2>&1 || abort "iw isn't installed" 255
ip -V >/dev/null 2>&1 || abort "ip isn't installed" 255

function printVersion {
    echo -e "uWifi v$uWifiVersion"    
    echo -e "\t$(dhcpcd --version | head -n 1) $(dhcpcd --version | tail -n 1)"
    echo -e "\t$(ip -V)"
    echo -e "\t$(iw --version)"
    echo -e "\t$(wpa_supplicant -v | head -n 1)"
}

function printInterfaces {
    ip link | grep ether -B 1 | grep -v link | grep -v "\--" | while read line
    do
        interface=$(echo $line | cut -d ":" -f 2 | cut -d " " -f 2)
        iw $interface info >/dev/null 2>&1 && echo $interface
    done
}

function getAvailableWirelessNetWork {
    parser='\
        $1 == "BSS" {
          MAC = substr($2,0,17)
          wifi[MAC]["enc"] = "NONE"
        }
        
        $1 == "SSID:" {
          wifi[MAC]["SSID"] = $2
        }
        
        $1 == "signal:" {
          wifi[MAC]["signal"] = $2
        }
        
        $1 == "WEP:" {
          wifi[MAC]["enc"] = "WEP"
        }
        
        $1 == "WPA:" {
          wifi[MAC]["enc"] = "WPA"
        }
        
        $1 == "RSN:" {
          wifi[MAC]["enc"] = "WPA2"
        }
        
        END {
          for (w in wifi) {
            printf "%s\t%s dBm\t%s\t%s\n",w,wifi[w]["signal"],wifi[w]["enc"],wifi[w]["SSID"]
          }
        }
    '
    
    ip link set dev "$1" up
    scanOutput=`iw dev "$1" scan | grep -v "BSS Load" | awk "$parser"`
    echo "$scanOutput" | sort --key 2 --reverse --numeric-sort
}

function printAvailableWirelessNetwork {
    printInterfaces | while read interface
    do
        echo -e "$interface:"
        i=1
        getAvailableWirelessNetWork $interface | while read network_line
        do
            echo -e "\t$i\t$network_line"
            i=$((i+1))
        done
    done
}

function getNonRootUserName {
    pid=$(echo $$ | cut -d " " -f 2)
    i=1
    username=$(ps faux | grep $pid | grep -v "grep" | cut -d " " -f 1)
    if [ $username = "root" ]
    then
        while [ $username = "root" ]
        do
            username=$(ps faux | grep $pid -B $i| grep -v "grep" | head -n 1 | cut -d " " -f 1)
            i=$((i+1))
        done
        echo $username
    
    else
        echo $username
    fi
}

if [ $# -eq "0" ]
then
    abort "Nothing to do" 0
elif [ $1 = "version" ]
then
    printVersion
elif [ $1 = "interfaces" ]
then
    printInterfaces
elif [ $1 = "networks" ]
then
    printAvailableWirelessNetwork
    getNonRootUserName
else
  abort "Unknown command" 255
fi
